---
name: magazzino_keycloak_setup

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: magazzino_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      JAVA_OPTS_APPEND: "-Dkeycloak.profile.feature.admin_fine_grained_authz=enabled"
    ports:
      - 8081:8080
      - 9000:9000
#    volumes:
#      - ./keycloak-config:/opt/keycloak/data/import
    command:
      - "start-dev"
      - "--health-enabled=true"
#      - "--import-realm"
    healthcheck:
      test: "exec 3<>/dev/tcp/localhost/9000 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'"
      interval: 1s
      timeout: 1s
      retries: 20
      start_period: 5s

      #      podman|docker run --name keycloak_unoptimized -p 8080:8080 \
      #      -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=change_me \
      #      -v /path/to/realm/data:/opt/keycloak/data/import \
      #      quay.io/keycloak/keycloak:latest \
      #      start-dev --import-realm

#
  keycloak-config:
    image: adorsys/keycloak-config-cli:6.1.5-25.0.1
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      KEYCLOAK_URL: http://keycloak:8080/
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin123
      IMPORT_FILES_LOCATIONS: '/config/*'
    volumes:
      - ./keycloak-config:/config
